var daftar_surat = [
    //{"no_surat":1,"nama_surat":"Al Fatihah","arti_surat":"Pembukaan","ayat":7,"urutan":5,"startAyat":null,"endAyat":null,"jenis":"Makkiyah"},
    { "no_surat": 2, "nama_surat": "Al Baqarah", "arti_surat": "Sapi betina", "ayat": 286, "urutan": 87, "startAyat": 0, "endAyat": 286, "jenis": "Madaniyah" },
    { "no_surat": 3, "nama_surat": "Ali Imran", "arti_surat": "Keluarga Imran", "ayat": 200, "urutan": 89, "startAyat": 286, "endAyat": 486, "jenis": "Madaniyah" },
    /*{"no_surat":4,"nama_surat":"An Nisaa'","arti_surat":"Wanita","ayat":176,"urutan":92,"startAyat":486,"endAyat":662,"jenis":"Madaniyah"},
    {"no_surat":5,"nama_surat":"Al Maa idah","arti_surat":"Hidangan","ayat":120,"urutan":112,"startAyat":662,"endAyat":782,"jenis":"Madaniyah"},
    {"no_surat":6,"nama_surat":"Al An'aam","arti_surat":"Binatang ternak","ayat":165,"urutan":55,"startAyat":782,"endAyat":947,"jenis":"Makkiyah"},
    {"no_surat":7,"nama_surat":"Al A'raaf","arti_surat":"Tempat tertinggi","ayat":206,"urutan":39,"startAyat":947,"endAyat":1153,"jenis":"Makkiyah"},
    {"no_surat":8,"nama_surat":"Al Anfaal","arti_surat":"Rampasan perang","ayat":75,"urutan":88,"startAyat":1153,"endAyat":1228,"jenis":"Madaniyah"},
    {"no_surat":9,"nama_surat":"At Taubah","arti_surat":"Pengampunan","ayat":129,"urutan":113,"startAyat":1228,"endAyat":1357,"jenis":"Madaniyah"},
    {"no_surat":10,"nama_surat":"Yunus","arti_surat":"Yunus","ayat":109,"urutan":51,"startAyat":1357,"endAyat":1466,"jenis":"Makkiyah"},
    {"no_surat":11,"nama_surat":"Hud","arti_surat":"Huud","ayat":123,"urutan":52,"startAyat":1466,"endAyat":1589,"jenis":"Makkiyah"},
    {"no_surat":12,"nama_surat":"Yusuf","arti_surat":"Yusuf","ayat":111,"urutan":53,"startAyat":1589,"endAyat":1700,"jenis":"Makkiyah"},
    {"no_surat":13,"nama_surat":"Ar Ra'd","arti_surat":"Guruh","ayat":43,"urutan":96,"startAyat":1700,"endAyat":1743,"jenis":"Madaniyah"},
    {"no_surat":14,"nama_surat":"Ibrahim","arti_surat":"Ibrahim","ayat":52,"urutan":72,"startAyat":1743,"endAyat":1795,"jenis":"Makkiyah"},
    {"no_surat":15,"nama_surat":"Al Hijr","arti_surat":"Al-Hijr","ayat":99,"urutan":54,"startAyat":1795,"endAyat":1894,"jenis":"Makkiyah"},
    {"no_surat":16,"nama_surat":"An Nahl","arti_surat":"Lebah","ayat":128,"urutan":70,"startAyat":1894,"endAyat":2022,"jenis":"Makkiyah"},
    {"no_surat":17,"nama_surat":"Al Isra'","arti_surat":"Memperjalankan di malam hari","ayat":111,"urutan":50,"startAyat":2022,"endAyat":2133,"jenis":"Makkiyah"},
    {"no_surat":18,"nama_surat":"Al Kahfi","arti_surat":"Gua","ayat":110,"urutan":69,"startAyat":2133,"endAyat":2243,"jenis":"Makkiyah"},
    {"no_surat":19,"nama_surat":"Maryam","arti_surat":"Maryam","ayat":98,"urutan":44,"startAyat":2243,"endAyat":2341,"jenis":"Makkiyah"},
    {"no_surat":20,"nama_surat":"Thaha","arti_surat":"Thaha","ayat":135,"urutan":45,"startAyat":2341,"endAyat":2476,"jenis":"Makkiyah"},
    {"no_surat":21,"nama_surat":"Al Anbiyaa'","arti_surat":"Nabi-nabi","ayat":112,"urutan":73,"startAyat":2476,"endAyat":2588,"jenis":"Makkiyah"},
    {"no_surat":22,"nama_surat":"Al Hajj","arti_surat":"Haji","ayat":78,"urutan":103,"startAyat":2588,"endAyat":2666,"jenis":"Madaniyah"},
    {"no_surat":23,"nama_surat":"Al Mu'minuun","arti_surat":"Orang-orang yang beriman","ayat":118,"urutan":74,"startAyat":2666,"endAyat":2784,"jenis":"Makkiyah"},
    {"no_surat":24,"nama_surat":"An Nuur","arti_surat":"Cahaya","ayat":64,"urutan":102,"startAyat":2784,"endAyat":2848,"jenis":"Madaniyah"},
    {"no_surat":25,"nama_surat":"Al Furqaan","arti_surat":"Pembeda","ayat":77,"urutan":42,"startAyat":2848,"endAyat":2925,"jenis":"Makkiyah"},
    {"no_surat":26,"nama_surat":"Asy Syu'araa'","arti_surat":"Para penyair","ayat":227,"urutan":47,"startAyat":2925,"endAyat":3152,"jenis":"Makkiyah"},
    {"no_surat":27,"nama_surat":"An Naml","arti_surat":"Semut","ayat":93,"urutan":48,"startAyat":3152,"endAyat":3245,"jenis":"Makkiyah"},
    {"no_surat":28,"nama_surat":"Al Qashash","arti_surat":"Cerita-cerita","ayat":88,"urutan":49,"startAyat":3245,"endAyat":3333,"jenis":"Makkiyah"},
    {"no_surat":29,"nama_surat":"Al Ankabut","arti_surat":"Laba-laba","ayat":69,"urutan":85,"startAyat":3333,"endAyat":3402,"jenis":"Makkiyah"},
    {"no_surat":30,"nama_surat":"Ar Ruum","arti_surat":"Bangsa Rumawi","ayat":60,"urutan":84,"startAyat":3402,"endAyat":3462,"jenis":"Makkiyah"},
    {"no_surat":31,"nama_surat":"Luqman","arti_surat":"Luqman","ayat":34,"urutan":57,"startAyat":3462,"endAyat":3496,"jenis":"Makkiyah"},
    {"no_surat":32,"nama_surat":"As Sajadah","arti_surat":"Sujud","ayat":30,"urutan":75,"startAyat":3496,"endAyat":3526,"jenis":"Makkiyah"},
    {"no_surat":33,"nama_surat":"Al Ahzab","arti_surat":"Golongan yang bersekutu","ayat":73,"urutan":90,"startAyat":3526,"endAyat":3599,"jenis":"Madaniyah"},
    {"no_surat":34,"nama_surat":"Saba'","arti_surat":"Kaum Saba'","ayat":54,"urutan":58,"startAyat":3599,"endAyat":3653,"jenis":"Makkiyah"},
    {"no_surat":35,"nama_surat":"Faathir","arti_surat":"Pencipta","ayat":45,"urutan":43,"startAyat":3653,"endAyat":3698,"jenis":"Makkiyah"},
    {"no_surat":36,"nama_surat":"Yaa Siin","arti_surat":"Yaa siin","ayat":83,"urutan":41,"startAyat":3698,"endAyat":3781,"jenis":"Makkiyah"},
    {"no_surat":37,"nama_surat":"Ash Shaffaat","arti_surat":"Yang bershaf-shaf","ayat":182,"urutan":56,"startAyat":3781,"endAyat":3963,"jenis":"Makkiyah"},
    {"no_surat":38,"nama_surat":"Shaad","arti_surat":"Shaad","ayat":88,"urutan":38,"startAyat":3963,"endAyat":4051,"jenis":"Makkiyah"},
    {"no_surat":39,"nama_surat":"Az Zumar","arti_surat":"Rombongan-rombongan","ayat":75,"urutan":59,"startAyat":4051,"endAyat":4126,"jenis":"Makkiyah"},
    {"no_surat":40,"nama_surat":"Al Mu'min","arti_surat":"Orang yang beriman","ayat":85,"urutan":60,"startAyat":4126,"endAyat":4211,"jenis":"Makkiyah"},
    {"no_surat":41,"nama_surat":"Fush Shilat","arti_surat":"Yang dijelaskan","ayat":54,"urutan":61,"startAyat":4211,"endAyat":4265,"jenis":"Makkiyah"},
    {"no_surat":42,"nama_surat":"Asy Syuura","arti_surat":"Musyawarat","ayat":53,"urutan":62,"startAyat":4265,"endAyat":4318,"jenis":"Makkiyah"},
    {"no_surat":43,"nama_surat":"Az Zukhruf","arti_surat":"Perhiasan","ayat":89,"urutan":63,"startAyat":4318,"endAyat":4407,"jenis":"Makkiyah"},
    {"no_surat":44,"nama_surat":"Ad Dukhaan","arti_surat":"Kabut","ayat":59,"urutan":64,"startAyat":4407,"endAyat":4466,"jenis":"Makkiyah"},
    {"no_surat":45,"nama_surat":"Al Jaatsiyah","arti_surat":"Yang berlutut","ayat":37,"urutan":65,"startAyat":4466,"endAyat":4503,"jenis":"Makkiyah"},
    {"no_surat":46,"nama_surat":"Al Ahqaaf","arti_surat":"Bukit-bukit pasir","ayat":35,"urutan":66,"startAyat":4503,"endAyat":4538,"jenis":"Makkiyah"},
    {"no_surat":47,"nama_surat":"Muhammad","arti_surat":"Nabi Muhammad SAW.","ayat":38,"urutan":95,"startAyat":4538,"endAyat":4576,"jenis":"Madaniyah"},
    {"no_surat":48,"nama_surat":"Al Fath","arti_surat":"Kemenangan","ayat":29,"urutan":111,"startAyat":4576,"endAyat":4605,"jenis":"Madaniyah"},
    {"no_surat":49,"nama_surat":"Al Hujurat","arti_surat":"Kamar-kamar","ayat":18,"urutan":106,"startAyat":4605,"endAyat":4623,"jenis":"Madaniyah"},
    {"no_surat":50,"nama_surat":"Qaaf","arti_surat":"Qaaf","ayat":45,"urutan":34,"startAyat":4623,"endAyat":4668,"jenis":"Makkiyah"},
    {"no_surat":51,"nama_surat":"Adz Dzaariyaat","arti_surat":"Angin yang menerbangkan","ayat":60,"urutan":67,"startAyat":4668,"endAyat":4728,"jenis":"Makkiyah"},
    {"no_surat":52,"nama_surat":"Ath Thuur","arti_surat":"Bukit","ayat":49,"urutan":76,"startAyat":4728,"endAyat":4777,"jenis":"Makkiyah"},
    {"no_surat":53,"nama_surat":"An Najm","arti_surat":"Bintang","ayat":62,"urutan":23,"startAyat":4777,"endAyat":4839,"jenis":"Makkiyah"},
    {"no_surat":54,"nama_surat":"Al Qamar","arti_surat":"Bulan","ayat":55,"urutan":37,"startAyat":4839,"endAyat":4894,"jenis":"Makkiyah"},
    {"no_surat":55,"nama_surat":"Ar Rahmaan","arti_surat":"Yang Maha Pemurah","ayat":78,"urutan":97,"startAyat":4894,"endAyat":4972,"jenis":"Madaniyah"},
    {"no_surat":56,"nama_surat":"Al Waaqiah","arti_surat":"Hari Kiamat","ayat":96,"urutan":46,"startAyat":4972,"endAyat":5068,"jenis":"Makkiyah"},
    {"no_surat":57,"nama_surat":"Al Hadiid","arti_surat":"Besi","ayat":29,"urutan":94,"startAyat":5068,"endAyat":5097,"jenis":"Madaniyah"},
    {"no_surat":58,"nama_surat":"Al Mujaadilah","arti_surat":"Wanita yang mengajukan gugatan","ayat":22,"urutan":105,"startAyat":5097,"endAyat":5119,"jenis":"Madaniyah"},
    {"no_surat":59,"nama_surat":"Al Hasyr","arti_surat":"Pengusiran","ayat":24,"urutan":101,"startAyat":5119,"endAyat":5143,"jenis":"Madaniyah"},
    {"no_surat":60,"nama_surat":"Al Mumtahanah","arti_surat":"Perempuan yang diuji","ayat":13,"urutan":91,"startAyat":5143,"endAyat":5156,"jenis":"Madaniyah"},
    {"no_surat":61,"nama_surat":"Ash Shaff","arti_surat":"Barisan","ayat":14,"urutan":109,"startAyat":5156,"endAyat":5170,"jenis":"Madaniyah"},
    {"no_surat":62,"nama_surat":"Al Jumu'ah","arti_surat":"Hari Jum'at","ayat":11,"urutan":110,"startAyat":5170,"endAyat":5181,"jenis":"Madaniyah"},
    {"no_surat":63,"nama_surat":"Al Munaafiquun","arti_surat":"Orang-orang munafik","ayat":11,"urutan":104,"startAyat":5181,"endAyat":5192,"jenis":"Madaniyah"},
    {"no_surat":64,"nama_surat":"At Taghaabun","arti_surat":"Hari ditampakkan segala kesalahan","ayat":18,"urutan":108,"startAyat":5192,"endAyat":5210,"jenis":"Madaniyah"},
    {"no_surat":65,"nama_surat":"Ath Thalaaq","arti_surat":"Talak","ayat":12,"urutan":99,"startAyat":5210,"endAyat":5222,"jenis":"Madaniyah"},
    {"no_surat":66,"nama_surat":"At Tahrim","arti_surat":"Mengharamkan","ayat":12,"urutan":107,"startAyat":5222,"endAyat":5234,"jenis":"Madaniyah"},
    {"no_surat":67,"nama_surat":"Al Mulk","arti_surat":"Kerajaan","ayat":30,"urutan":77,"startAyat":5234,"endAyat":5264,"jenis":"Makkiyah"},
    {"no_surat":68,"nama_surat":"Al Qalam","arti_surat":"Kalam","ayat":52,"urutan":2,"startAyat":5264,"endAyat":5316,"jenis":"Makkiyah"},
    {"no_surat":69,"nama_surat":"Al Haaqqah","arti_surat":"Hari kiamat","ayat":52,"urutan":78,"startAyat":5316,"endAyat":5368,"jenis":"Makkiyah"},
    {"no_surat":70,"nama_surat":"Al Ma'aarij","arti_surat":"Tempat-tempat naik","ayat":44,"urutan":79,"startAyat":5368,"endAyat":5412,"jenis":"Makkiyah"},
    {"no_surat":71,"nama_surat":"Nuh","arti_surat":"Nabi Nuh","ayat":28,"urutan":71,"startAyat":5412,"endAyat":5440,"jenis":"Makkiyah"},
    {"no_surat":72,"nama_surat":"Al Jin","arti_surat":"Jin","ayat":28,"urutan":40,"startAyat":5440,"endAyat":5468,"jenis":"Makkiyah"},
    {"no_surat":73,"nama_surat":"Al Muzzammil","arti_surat":"Orang yang berselimut","ayat":20,"urutan":3,"startAyat":5468,"endAyat":5488,"jenis":"Makkiyah"},
    {"no_surat":74,"nama_surat":"Al Muddatstsir","arti_surat":"Orang yang berkemul","ayat":56,"urutan":4,"startAyat":5488,"endAyat":5544,"jenis":"Makkiyah"},
    {"no_surat":75,"nama_surat":"Al Qiyaamah","arti_surat":"Hari Kiamat","ayat":40,"urutan":31,"startAyat":5544,"endAyat":5584,"jenis":"Makkiyah"},
    {"no_surat":76,"nama_surat":"Al Insaan","arti_surat":"Manusia","ayat":31,"urutan":98,"startAyat":5584,"endAyat":5615,"jenis":"Madaniyah"},
    {"no_surat":77,"nama_surat":"Al Mursalaat","arti_surat":"Malaikat-malaikat yang diutus","ayat":50,"urutan":33,"startAyat":5615,"endAyat":5665,"jenis":"Makkiyah"},
    {"no_surat":78,"nama_surat":"An Naba'","arti_surat":"Berita besar","ayat":40,"urutan":80,"startAyat":5665,"endAyat":5705,"jenis":"Makkiyah"},
    {"no_surat":79,"nama_surat":"An Naazi'aat","arti_surat":"Para malaikat yang mencabut","ayat":46,"urutan":81,"startAyat":5705,"endAyat":5751,"jenis":"Makkiyah"},
    {"no_surat":80,"nama_surat":"'Abasa","arti_surat":"Ia bermuka masam","ayat":42,"urutan":24,"startAyat":5751,"endAyat":5793,"jenis":"Makkiyah"},
    {"no_surat":81,"nama_surat":"At Takwir","arti_surat":"Menggulung","ayat":29,"urutan":7,"startAyat":5793,"endAyat":5822,"jenis":"Makkiyah"},
    {"no_surat":82,"nama_surat":"Al Infithar","arti_surat":"Terbelah","ayat":19,"urutan":82,"startAyat":5822,"endAyat":5841,"jenis":"Makkiyah"},
    {"no_surat":83,"nama_surat":"Al Muthaffifiin","arti_surat":"Orang-orang yang curang","ayat":36,"urutan":86,"startAyat":5841,"endAyat":5877,"jenis":"Makkiyah"},
    {"no_surat":84,"nama_surat":"Al Insyiqaaq","arti_surat":"Terbelah","ayat":25,"urutan":83,"startAyat":5877,"endAyat":5902,"jenis":"Makkiyah"},
    {"no_surat":85,"nama_surat":"Al Buruuj","arti_surat":"Gugusan bintang","ayat":22,"urutan":27,"startAyat":5902,"endAyat":5924,"jenis":"Makkiyah"},
    {"no_surat":86,"nama_surat":"Ath Thaariq","arti_surat":"Yang datang di malam hari","ayat":17,"urutan":36,"startAyat":5924,"endAyat":5941,"jenis":"Makkiyah"},
    {"no_surat":87,"nama_surat":"Al A'laa","arti_surat":"Yang paling tinggi","ayat":19,"urutan":8,"startAyat":5941,"endAyat":5960,"jenis":"Makkiyah"},
    {"no_surat":88,"nama_surat":"Al Ghaasyiyah","arti_surat":"Hari pembalasan","ayat":26,"urutan":68,"startAyat":5960,"endAyat":5986,"jenis":"Makkiyah"},
    {"no_surat":89,"nama_surat":"Al Fajr","arti_surat":"Fajar","ayat":30,"urutan":10,"startAyat":5986,"endAyat":6016,"jenis":"Makkiyah"},
    {"no_surat":90,"nama_surat":"Al Balad","arti_surat":"Negeri","ayat":20,"urutan":35,"startAyat":6016,"endAyat":6036,"jenis":"Makkiyah"},
    {"no_surat":91,"nama_surat":"Asy Syams","arti_surat":"Matahari","ayat":15,"urutan":26,"startAyat":6036,"endAyat":6051,"jenis":"Makkiyah"},
    {"no_surat":92,"nama_surat":"Al Lail","arti_surat":"Malam","ayat":21,"urutan":9,"startAyat":6051,"endAyat":6072,"jenis":"Makkiyah"},
    {"no_surat":93,"nama_surat":"Ad Dhuhaa","arti_surat":"Waktu matahari sepenggalan naik","ayat":11,"urutan":11,"startAyat":6072,"endAyat":6083,"jenis":"Makkiyah"},
    {"no_surat":94,"nama_surat":"Alam Nasyrah","arti_surat":"Melapangkan","ayat":8,"urutan":12,"startAyat":6083,"endAyat":6091,"jenis":"Makkiyah"},
    {"no_surat":95,"nama_surat":"At Tiin","arti_surat":"Buah tin","ayat":8,"urutan":28,"startAyat":6091,"endAyat":6099,"jenis":"Makkiyah"},
    {"no_surat":96,"nama_surat":"Al 'Alaq","arti_surat":"Segumpal darah","ayat":19,"urutan":1,"startAyat":6099,"endAyat":6118,"jenis":"Makkiyah"},
    {"no_surat":97,"nama_surat":"Al Qadar","arti_surat":"Kemuliaan","ayat":5,"urutan":25,"startAyat":6118,"endAyat":6123,"jenis":"Makkiyah"},
    {"no_surat":98,"nama_surat":"Al Bayyinah","arti_surat":"Bukti","ayat":8,"urutan":100,"startAyat":6123,"endAyat":6131,"jenis":"Madaniyah"},
    {"no_surat":99,"nama_surat":"Al Zalzalah","arti_surat":"Kegoncangan","ayat":8,"urutan":93,"startAyat":6131,"endAyat":6139,"jenis":"Madaniyah"},
    {"no_surat":100,"nama_surat":"Al 'Aadiyaat","arti_surat":"Kuda perang yang berlari kencang","ayat":11,"urutan":14,"startAyat":6139,"endAyat":6150,"jenis":"Makkiyah"},
    {"no_surat":101,"nama_surat":"Al Qaari'ah","arti_surat":"Hari Kiamat","ayat":11,"urutan":30,"startAyat":6150,"endAyat":6161,"jenis":"Makkiyah"},
    {"no_surat":102,"nama_surat":"At Takaatsur","arti_surat":"Bermegah-megahan","ayat":8,"urutan":16,"startAyat":6161,"endAyat":6169,"jenis":"Makkiyah"},
    {"no_surat":103,"nama_surat":"Al 'Ashr","arti_surat":"Masa","ayat":3,"urutan":13,"startAyat":6169,"endAyat":6172,"jenis":"Makkiyah"},
    {"no_surat":104,"nama_surat":"Al Humazah","arti_surat":"Pengumpat","ayat":9,"urutan":32,"startAyat":6172,"endAyat":6181,"jenis":"Makkiyah"},
    {"no_surat":105,"nama_surat":"Al Fiil","arti_surat":"Gajah","ayat":5,"urutan":19,"startAyat":6181,"endAyat":6186,"jenis":"Makkiyah"},
    {"no_surat":106,"nama_surat":"Al Quraisy","arti_surat":"Suku Quraisy","ayat":4,"urutan":29,"startAyat":6186,"endAyat":6190,"jenis":"Makkiyah"},
    {"no_surat":107,"nama_surat":"Al Maa'un","arti_surat":"Barang-barang yang berguna","ayat":7,"urutan":17,"startAyat":6190,"endAyat":6197,"jenis":"Makkiyah"},
    {"no_surat":108,"nama_surat":"Al Kautsar","arti_surat":"Nikmat yang banyak","ayat":3,"urutan":15,"startAyat":6197,"endAyat":6200,"jenis":"Makkiyah"},
    {"no_surat":109,"nama_surat":"Al Kaafiruun","arti_surat":"Orang-orang kafir","ayat":6,"urutan":18,"startAyat":6200,"endAyat":6206,"jenis":"Makkiyah"},
    {"no_surat":110,"nama_surat":"An Nashr","arti_surat":"Pertolongan","ayat":3,"urutan":114,"startAyat":6206,"endAyat":6209,"jenis":"Madaniyah"},
    {"no_surat":111,"nama_surat":"Al Lahab","arti_surat":"Gejolak api","ayat":5,"urutan":6,"startAyat":6209,"endAyat":6214,"jenis":"Makkiyah"},
    {"no_surat":112,"nama_surat":"Al Ikhlash","arti_surat":"Memurnikan Keesaan Allah","ayat":4,"urutan":22,"startAyat":6214,"endAyat":6218,"jenis":"Makkiyah"},
    {"no_surat":113,"nama_surat":"Al Falaq","arti_surat":"Waktu subuh","ayat":5,"urutan":20,"startAyat":6218,"endAyat":6223,"jenis":"Makkiyah"} */
]